---
- name: Get vendor id
  xml:
    path: "/tmp/{{ item }}.xml"
    xpath: /device/capability/vendor
    content: attribute
  register: xmlresp

- name: Set vendor_id
  set_fact:
    vendor_id: "{{ xmlresp.matches[0].vendor.id[2:] }}"

- name: Get product id
  xml:
    path: "/tmp/{{ item }}.xml"
    xpath: /device/capability/product
    content: attribute
  register: xmlresp

- name: Set product_id
  set_fact:
    product_id: "{{ xmlresp.matches[0].product.id[2:] }}"

- name: Set pci_id
  set_fact:
    pci_id: "{{ vendor_id }}:{{ product_id }},"

- name: Add pci_id to modprobe_conf
  set_fact:
    modprobe_conf: "{{ modprobe_conf }}{{ pci_id }}"
