all:
  hosts:
    desktop:
      ansible_connection: local
  vars:
    user_groups:
      - wheel
      - wireshark
      - libvirt
      - docker
    systemd_user_units:
      - ssh-agent.service
      - nas-backup.timer
      #- nas-prune.timer

    smb_share: //nas.local/share
    smb_mount: "{{ home }}/nas"

    br_primary_int: br0
    br_secondary_int: "{{ ansible_default_ipv4.interface }}"
    br_libvirt_net: bridge-network

    # virsh nodedev-list | grep pci
    vfio_vms:
      - name: win10-vfio
        disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
        mouse: /dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse
        keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
        pci_devices:
          - pci_0000_09_00_0
          - pci_0000_09_00_1
          - pci_0000_0b_00_3
          - pci_0000_0b_00_4

      - name: win10-dtx
        #disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
        #mouse: /dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse
        keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
        pci_devices:
          - pci_0000_00_02_6
          - pci_0000_00_1f_0

    cpu_hook_vm_names:
      - win10-vfio

    docker_install_compose: true
