all:
  hosts:
    desktop:
      ansible_connection: local
  vars:
    user_groups:
      - wheel
      - wireshark
      - libvirt
      #- docker

    vfio: yes
    # virsh nodedev-list | grep pci
    vfio_vm_name: win10-vfio
    vfio_vm_disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
    vfio_vm_mouse: /dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse
    vfio_vm_keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
    vfio_pci_devices:
      - pci_0000_00_1b_0
      - pci_0000_06_00_0

    libvirt_hooks: yes

    cpu_governor_hooks: yes
    cpu_hook_vm_names:
      - "{{ vfio_vm_name }}"
    
    samba: yes
    samba_share: //nas.local/share
    samba_mountpoint: "/home/{{ user }}/nas"

    configs: yes
    systemd_user_units:
      - ssh-agent.service
      - nas-backup.timer
      #- nas-prune.timer

    bridge_interface: yes
    bridge_interface_name: br0
    bridge_interface_slave: enp1s0
    libvirt_bridge_network: bridge-network
