all:
  hosts:
    desktop:
      #ansible_host: localhost
      ansible_connection: local
  vars:
    vfio: yes
    # virsh nodedev-list | grep pci
    vfio_vm_name: win10-vfio
    vfio_vm_disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
      #vfio_vm_mouse: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
      #vfio_vm_keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
    vfio_pci_devices:
      - pci_0000_00_1b_0
      - pci_0000_06_00_0

    libvirt_hooks: yes

    cpu_governor_hooks: yes
    cpu_hook_vm_names:
      - "{{ vfio_vm_name }}"

    evdev_passthrough: yes
    evdev_devices:
      - /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
