all:
  hosts:
    desktop:
      ansible_connection: local
  vars:
    configs: yes
    user_groups:
      - wheel
      - wireshark
      - libvirt
      #- docker
    systemd_user_units:
      - ssh-agent.service
      - nas-backup.timer
      #- nas-prune.timer

    samba: yes
    samba_share: //nas.local/share
    samba_mountpoint: "/home/{{ user }}/nas"

    bridge_interface: yes
    br_primary_int: br0
    br_secondary_int: enp1s0
    br_libvirt_net: bridge-network

    vfio: yes
    # virsh nodedev-list | grep pci
    vfio_vms:
      - name: win10-vfio
        disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
        mouse: /dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse
        keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
        pci_devices:
          - pci_0000_00_1b_0
          - pci_0000_06_00_0

      - name: win10-dtx
        #disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
        #mouse: /dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse
        keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
        pci_devices:
          - pci_0000_00_02_6
          - pci_0000_00_1f_0

    libvirt_hooks: yes

    cpu_governor_hooks: yes
    cpu_hook_vm_names:
      - "{{ vfio_vm_name }}"
