all:
  hosts:
    desktop:
      ansible_host: localhost
  vars:
    #ansible_ssh_user: bsharkey

    vfio: no
    pci_ids: 10de:10f0,10de:1b80

    vm_name: win10-test
    libvirt_hooks: yes
    cpu_governor_hook: yes
