all:
  hosts:
    desktop:
      ansible_connection: local
      user_groups:
        - wheel
        - wireshark
        - libvirt
        - docker
      systemd_user_units:
        - ssh-agent.service
        - nas-backup.timer
        #- nas-prune.timer

      docker_install_compose: true

      smb_share: //nas.local/share
      smb_mount: "{{ home }}/nas"

      br_primary_int: br0
      br_secondary_int: "{{ ansible_default_ipv4.interface }}"
      br_libvirt_net: bridge-network

      # lspci -n
      vfio_bind_ids:
        - 10de:1b80
        - 10de:10f0
        - 1102:0012
      
      passthrough_vms:
        - name: win10-vfio
          cores: 1
          threads: 1
          memory: 1
          disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
          mouse: /dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse
          keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
          cpu_governor_hook: yes
          # lspci
          pci_devices:
            #- "09:00.0"
            #- "09:00.1"
            - "05:00.0"

        #- name: win10-dtx
        #  #disk: /dev/disk/by-id/wwn-0x500a0751e14b33a3
        #  #mouse: /dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse
        #  keyboard: /dev/input/by-id/usb-0d3d_USBPS2-event-kbd
        #  pci_devices:
        #    - pci_0000_00_02_6
        #    - pci_0000_00_1f_0
