---
- hosts: desktop
  become: yes
  pre_tasks:
    - name: Get username
      command: id -u -n
      register: result
      become: no

    - name: Set user var
      set_fact:
        user: "{{ result.stdout }}"

    - name: Get uid
      command: id -u
      register: result
      become: no

    - name: Set uid var
      set_fact:
        uid: "{{ result.stdout }}"

    - name: Get gid
      command: id -g
      register: result
      become: no

    - name: Set gid var
      set_fact:
        gid: "{{ result.stdout }}"

    - name: Install dependencies
      dnf:
        name:
          - python3-libselinux
          - python3-lxml

  roles:
    #- packages
    #- vfio
    #- libvirt-hooks
    #- cpu-governor-hooks
    # Not needed anymore https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Passing_keyboard/mouse_via_Evdev
    #- evdev-passthrough
    #- vm-vfio
    #- configs
    #- samba
    - bridge-interface 
