---
- hosts: localhost
  become: yes

    #vars_prompt:
    #  - name: vm_name
    #    prompt: Enter virtual machine name
    #    private: no

  roles:
    #- packages
    - vfio
    #- libvirt-hooks
    #- cpu-governor-hook
