---
- hosts: desktop
  become: yes
  pre_tasks:
    - name: Get username
      command: id -u -n
      register: result
      become: no

    - name: Set user var
      set_fact:
        user: "{{ result.stdout }}"

    - name: Get uid
      command: id -u
      register: result
      become: no

    - name: Set uid var
      set_fact:
        uid: "{{ result.stdout }}"

    - name: Get gid
      command: id -g
      register: result
      become: no

    - name: Set gid var
      set_fact:
        gid: "{{ result.stdout }}"

  roles:
    - packages
    - docker
    - configs
    - samba
    - bridge-interface 
    - vfio
    - libvirt-hooks
    - cpu-governor-hooks
