---
# tasks file for samba
- name: Setup samba
  when: samba
  block:
    - name: Install cifs utils
      dnf:
        name: cifs-utils
        state: latest
    
    - name: Template samba credential file
      template:
        src: smbpasswd.j2
        dest: "/home/{{ user }}/.smbpasswd"
        mode: 0600
        force: yes

    - name: Create samba share mountpoint
      file:
        path: "{{ samba_mountpoint }}"
        state: directory
        mode: 0755
      become: no
    
    - name: Add samba share to fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ samba_share }} {{ samba_mountpoint }} cifs credentials=/home/{{ user }}/.smbpasswd,uid={{ uid }},gid={{ gid }},iocharset=utf8,vers=3"

    - name: Mount samba share
      command: mount -a
