---
# tasks file for configs
- name: Setup configs
  when: configs
  block:
    - name: Copy user configs
      synchronize:
        src: home/
        dest: "/home/{{ user }}"
        recursive: yes
    
    - name: Copy system configs
      synchronize:
        src: etc/
        dest: /etc
        recursive: yes
    
    - name: Reload all kernel modules
      systemd:
        name: systemd-modules-load
        state: restarted

    #- name: Reload all kernel variables
    #  systemd:
    #    name: systemd-sysctl
    #    state: restarted
    
    - name: Create auto login override dir structure
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        recurse: yes
        state: directory
    
    - name: Template auto login override config
      template:
        src: override.conf.j2
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    
    - name: Add user to groups
      user:
        name: "{{ user }}"
        groups: "{{ user_groups }}"
    
    - name: Enable systemd user units
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
        scope: user
      loop: systemd_user_units
