---
# tasks file for configs
- name: Setup configs
  when: configs
  block:
    - name: Add user to groups
      user:
        name: "{{ user }}"
        groups: "{{ user_groups }}"

    - name: Create user dirs
      file:
        path: "/home/{{ user }}/{{ item }}"
        state: directory
        recurse: yes
        mode: 0755
      loop:
        - Documents
        - Downloads
        - Pictures
        - Videos
        - Music
        - Desktop
        - Templates
        - Public
        - projects
        - .config/gtk-3.0
      become: no
    
    - name: Copy user configs
      synchronize:
        src: home/
        dest: "/home/{{ user }}"
        recursive: yes
      become: no
    
    - name: Template user bookmarks
      template:
        src: bookmarks.j2
        dest: "/home/{{ user }}/.config/gtk-3.0/bookmarks"
        force: yes
      become: no
    
    - name: Copy system configs
      synchronize:
        src: etc/
        dest: /etc
        recursive: yes

    - name: Reload all kernel modules
      systemd:
        name: systemd-modules-load
        state: restarted

    #- name: Reload all kernel variables
    #  systemd:
    #    name: systemd-sysctl
    #    state: restarted
    
    - name: Create auto login override dir structure
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        recurse: yes
        state: directory
    
    - name: Template auto login override config
      template:
        src: override.conf.j2
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf

    - name: Systemd user daemon reload
      systemd:
        daemon_reload: yes
    
    - name: Enable and start systemd user units
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
        scope: user
      loop: "{{ systemd_user_units }}"
      become: no

    - name: Clone wayweather repo
      git:
        repo: https://github.com/basharkey/wayweather
        dest: "/tmp/wayweather"
      become: no

    - name: Install wayweather
      shell: install.sh
      args:
        chdir: "/tmp/wayweather"
      become: no

    - name: Clone spotifyvctl repo
      git:
        repo: https://github.com/basharkey/spotifyvctl
        dest: /tmp/spotifyvctl

    - name: Copy spotifyvctl.py to path
      copy:
        src: /tmp/spotifyvctl/spotifyvctl.py
        dest: /usr/local/bin/spotifyvctl.py
        mode: 0755
