---
# tasks file for libvirt-hooks
- name: Install libvirt hooks
  when: libvirt_hooks
  block:
    - name: Check if libvirt hooks installed
      command: test -f /etc/libvirt/hooks/qemu

  rescue:
    - name: Create hooks directory
      file:
        path: /etc/libvirt/hooks/qemu.d/
        state: directory
        mode: 0755

    - name: Copy hooks script
      copy:
        src: qemu
        dest: /etc/libvirt/hooks/qemu
        mode: 0755

    - name: Restart service libvirtd
      service:
        name: libvirtd
        state: restarted
