---
# tasks file for bridge-interface
- name: Copy br_netfilter kernel module config
  copy:
    src: br_netfilter.conf
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: 0644

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Copy br_netfilter kernel variable config
  copy:
    src: 99-netfilter-bridge.conf
    dest: /etc/sysctl.d/99-netfilter-bridge.conf
    mode: 0755

- name: Reload all kernel variables
  systemd:
    name: systemd-sysctl
    state: restarted

# bridge interface will break local DHCP if STP is not enabled
- name: Create bridge interface
  nmcli:
    conn_name: "bridge-{{ br_primary_int }}"
    ifname: "{{ br_primary_int }}"
    type: bridge
    stp: yes
    state: present

- name: Attach main interface to bridge
  nmcli:
    conn_name: "{{ br_primary_int }}-slave-1"
    ifname: "{{ br_secondary_int }}"
    master: "{{ br_primary_int }}"
    type: bridge-slave
    state: present

- name: Ensure virtqemud is running
  systemd:
    name: virtqemud
    state: started

- name: Ensure virtnetworkd is running
  systemd:
    name: virtnetworkd
    state: started

- name: Generate libvirt bridge network definition var
  set_fact:
    bridge_template: "{{ lookup('template', 'bridge-network.xml.j2') }}"

- name: Add libvirt bridge network definition
  shell: "virsh net-define <(echo '{{ bridge_template | string }}')"
  register: result
  failed_when: result.rc != 0 and "network '" ~ br_libvirt_net ~ "' already exists" not in result.stderr

- name: Enable libvirt bridge network at boot
  command: "virsh net-autostart {{ br_libvirt_net }}"

- name: Start libvirt bridge network
  command: "virsh net-start {{ br_libvirt_net }}"
  register: result
  failed_when: result.rc != 0 and "network is already active" not in result.stderr
