---
# tasks file for bridge-interface
- name: Copy kernel module config
  copy:
    src: br_netfilter.conf
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: 0755

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Copy kernel variable config
  copy:
    src: 99-netfilter-bridge.conf
    dest: /etc/sysctl.d/99-netfilter-bridge.conf
    mode: 0755

- name: Set kernel variables
  sysctl:
    name: "{{ item }}"
    value: 0
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-arptables

- name: Create bridge interface
  nmcli:
    conn_name: bridge-br0
    ifname: br0
    type: bridge
    # solves long bootup times
    stp: no
    state: present

- name: Enslave main interface
  nmcli:
    conn_name: br-slave-1
    ifname: "{{ bridge_interface_slave }}"
    master: br0
    type: bridge-slave
    state: present
